
import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import typescript from "@rollup/plugin-typescript";

const isProd = process.env.BUILD === "production";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
    input: "./src/app.ts",
    output: {
        file: "./dist/app.js",
        sourcemap: "inline",
        sourcemapExcludeSources: isProd,
        format: "cjs",
        exports: "auto",
        banner
    },
    plugins: [
        typescript(),
        nodeResolve({ browser: true }),
        commonjs(),
        json(),
    ]
}